### ISSUE TITLE
code is not complete

### ISSUE THREAD

**Issue by tiantzp** [pokaxpoka/sunrise#2]
Dear authors, thank you very much for submitting the code of your outstanding work. In the paper of ‘Sunrise: a simple unified framework for ensemble learning in deep reinforcement learning’, you have tested the performance of your algorithm in DeepMind Control Suit. But there is no code in this repository, would you like to share the code with me. Thanks!

**Comment by pokaxpoka** [comment]
I need some time to prepare it but you can easily set up the codebase based on our SAC implementation and RAD https://github.com/MishaLaskin/rad
